# Site settings
title: UTD Event Data
email: pbrandt@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
  Funded by NSF RIDIR SBE-SMA-1539302
url: Jingnan92.github.io
baseurl: /UTDEventData

twitter_username: PatrickTBrandt
github_username:  Patrick T. Brandt

# Build settings
markdown: kramdown

# Other options
#permalink: blog/:year/:month/:title
#job.title: "Assistant Professor"
#excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
